jump-location:
  world: "world"
  x: 0
  y: 100
  z: 0

spawn-location:
  world: "world"
  x: 0
  y: 64
  z: 0

roles:
  Radahn: true
  Melina: true
  SansEclat: true
  Ranni: true
  Godrick: true
  Morgott: true
  Margit: true
  TemoinDeLaMort: true
