name: UHCPlugin
main: me.uhcplugin.Main
version: 1.0
api-version: 1.18
commands:

  uhctest:
    description: Commande de test pour voir si le plugin fonctionne
    usage: /uhctest
    permission: uhcplugin.uhctest

  startuhc:
    permissions:
      uhcplugin.startuhc:
        description: Permission pour démarrer l'UHC
        default: op

  setspawn:
    description: Définit le spawn de l'UHC
    usage: /setspawn
    permission: uhcplugin.setspawn

  setjump:
    description: Définit la zone de jump
    usage: /setjump
    permission: uhcplugin.setjump

  jump:
    description: Téléporte le joueur au jump
    usage: /jump
    permission: uhcplugin.jump

  spawn:
    description: Téléporte le joueur au spawn
    usage: /spawn
    permission: uhcplugin.spawn

  enduhc:
    description: "Forcer la fin de la partie UHC"
    usage: "/enduhc"
    permission: uhcplugin.enduhc
  permissions:
    uhcplugin.enduhc:
      description: "Permet de forcer la fin de la partie"
      default: op

  confirmstuff:
    description: "Confirme et sauvegarde le stuff du joueur."
    usage: "/confirmstuff"

  testparticles:
    description: "Teste l'affichage des particules sur Geyser"
    usage: "/testparticles"
    permission: uhcplugin.testparticles









