name: UHCPlugin
main: me.uhcplugin.Main
version: 1.0
api-version: 1.18
commands:
  startuhc:
    description: Démarre la partie UHC
    usage: /startuhc
    permission: uhcplugin.startuhc
  uhctest:
    description: Vérifie si le plugin fonctionne
    usage: /uhctest
  setspawn:
    description: Définit le spawn de l'UHC
    usage: /setspawn
  setjump:
    description: Définit la zone de jump
    usage: /setjump
  jump:
    description: Téléporte le joueur au jump
    usage: /jump
  spawn:
    description: Téléporte le joueur au spawn
    usage: /spawn
permissions:
  uhcplugin.startuhc:
    description: Permission pour démarrer l'UHC
    default: op
  uhcplugin.config:
    description: Permission pour modifier la configuration UHC
    default: op
  permissions:
    uhcplugin.config:
      description: Permission pour modifier la configuration UHC
      default: op


