name: UHCPlugin
main: me.uhcplugin.Main
version: 1.0
api-version: 1.18
commands:

  uhctest:
    description: Commande de test pour voir si le plugin fonctionne
    usage: /uhctest
    permission: uhcplugin.uhctest

  startuhc:
    permissions:
      uhcplugin.startuhc:
        description: Permission pour démarrer l'UHC
        default: op

  setspawn:
    description: Définit le spawn de l'UHC
    usage: /setspawn
    permission: uhcplugin.setspawn

  setjump:
    description: Définit la zone de jump
    usage: /setjump
    permission: uhcplugin.setjump

  jump:
    description: Téléporte le joueur au jump
    usage: /jump

  spawn:
    description: Téléporte le joueur au spawn
    usage: /spawn

  enduhc:
    description: "Forcer la fin de la partie UHC"
    usage: "/enduhc"
    permission: uhcplugin.enduhc
  permissions:
    uhcplugin.enduhc:
      description: "Permet de forcer la fin de la partie"
      default: op

  confirmstuff:
    description: "Confirme et sauvegarde le stuff du joueur."
    usage: "/confirmstuff"

  role:
    description: "Affiche ton rôle, ton camp et ta capacité"
    usage: "/role"

  checkrole:
    description: Permet aux admins de voir le rôle d’un joueur.
    usage: /checkrole <joueur>
    permission: uhcplugin.checkrole

  lecture:
    description: "Permet à Ranni d'analyser le rôle d'un joueur"
    usage: "/lecture <joueur>"

  soin:
    description: "Mélina soigne un joueur."
    usage: "/soin <joueur>"

  vision:
    description: "Mélina peut voir le camp d’un joueur."
    usage: "/vision <joueur>"

permissions:

  uhcplugin.checkrole:
    description: Permet aux admins de voir le rôle d’un joueur.
    default: true
